name: Deploy examples to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "examples/**"
      - ".github/workflows/deploy-examples.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "11.2.2"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all examples
        run: |
          cd ./examples
          pnpm run build

      - name: Prepare docs folder for GitHub Pages
        run: |
          rm -rf docs
          mkdir -p docs

          cp -r ./examples/dist ./docs/examples
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
